name: Change Issue Status on New Branch

on:
  create:
    branches:
      - '*'

jobs:
  update_issue_status:
    runs-on: ubuntu-latest
    steps:
      - name: Change issue status
        uses: octokit/request-action@v2
        with:
          route: GET /repos/:owner/:repo/commits/:commit_sha
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          commit_sha: ${{ github.sha }}
      
      - name: Get associated issue
        id: issue_info
        run: |
          issue_number=$(cat output.json | jq -r '.commit.message' | grep -oP '#\K\d+')
          echo "::set-output name=issue_number::$issue_number"

      - name: Update issue to Ready
        if: steps.issue_info.outputs.issue_number != ''
        uses: octokit/request-action@v2
        with:
          route: PATCH /repos/:owner/:repo/issues/:issue_number
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue_number: ${{ steps.issue_info.outputs.issue_number }}
          status: "Ready"
