name: Yeni Branch Oluşturuldu

on:
  push:
    branches:
      - "*" # Herhangi bir branch'e push olduğunda tetikler

jobs:
  yeni_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kod
        uses: actions/checkout@v3

      - name: Branch Bilgisi
        run: |
          echo "Yeni bir branch oluşturuldu!"
          echo "Branch ismi: ${{ github.ref }}"
