name: Issue Status Değişikliği İzleme
on:
  issues:
    types: [edited opened closed reopened synchronize ]  

jobs:
  track-issue-status:
    runs-on: ubuntu-latest
    steps:
      - name: Durum Değişikliği Bildirimi
        run: |
          echo "Bir issue'nun durumu değiştirildi."
          echo "Issue: #${{ github.event.issue.number }}"
          echo "Eski Durum: ${{ github.event.changes.state.from }}"
          echo "Yeni Durum: ${{ github.event.issue.state }}"
