name: Issue Status Change Logger

on:
  issues:
    types: [opened, closed, reopened, edited]

jobs:
  log_issue_status_change:
    runs-on: ubuntu-latest

    steps:
      - name: Log Issue Status Change
        run: |
          echo "Issue ID: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Changed From: ${{ github.event.changes }} to ${{ github.event.issue.state }}"
