name: Yeni Branch Aç ve Issue'ya Yorum Ekle

on:
  issues:
    types:
      - opened

jobs:
  create_branch_and_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Bilgilerini Al
        id: issue_data
        uses: actions/github-script@v6
        with:
          script: |
            return {
              "issue_number": context.payload.issue.number,
              "issue_title": context.payload.issue.title
            }

      - name: GitHub Reposunu Klonla
        uses: actions/checkout@v3

      - name: Yeni Branch Oluştur
        run: |
          branch_name="issue-${{ steps.issue_data.outputs.issue_number }}-${{ github.sha }}"
          git checkout -b $branch_name

      - name: Değişiklikleri Pushla
        run: |
          git push origin $branch_name

      - name: Issue'ya Yorum Ekle
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.issue_data.outputs.issue_number }}
          body: |
            Yeni branch açıldı: ${{ github.repository }}/tree/${{ branch_name }}
