name: Notify on Branch Creation
on:
  create:
    types:
      - branch  # Yalnızca yeni bir branch oluşturulduğunda tetiklenir

jobs:
  notify_branch_creation:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Information
        uses: actions/github-script@v6
        id: branch_info
        with:
          script: |
            return {
              "branch_name": context.ref.replace('refs/heads/', ''),
              "branch_creator": context.actor,
              "issue_number": context.issue.number if 'issue' in context else None
            }

      - name: Comment on Related Issue
        if: ${{ steps.branch_info.outputs.issue_number != null }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.branch_info.outputs.issue_number }}
          body: |
            @${{ steps.branch_info.outputs.branch_creator }} tarafından yeni bir branch oluşturuldu: `$branch_name`
